    public void communicateClient(RFCommConnectionImpl con) {
        OutputStream os, os2 = null;
        InputStream is, is2 = null;
        ObjectOutputStream oos = null;
        ObjectInputStream ois = null;
        GZIPOutputStream gzout = null;
        ByteArrayOutputStream bos = null;
        ByteArrayInputStream bis = null;
        try {
            os = con.openOutputStream();
            is = con.openInputStream();
            oos = new ObjectOutputStream(os);
            ois = new ObjectInputStream(is);
            bos = new ByteArrayOutputStream();
            RemoteDevice dev = con.getRemoteDevice();
            System.out.println(dev.getBluetoothAddress());
            KeyPairGenerator keyGen = KeyPairGenerator.getInstance("DH");
            AlgorithmParameterGenerator paramGen = AlgorithmParameterGenerator.getInstance("DH");
            paramGen.init(512, SecureRandom.getInstance("SHA1PRNG"));
            AlgorithmParameters params = paramGen.generateParameters();
            DHParameterSpec dhSpec = (DHParameterSpec) params.getParameterSpec(DHParameterSpec.class);
            keyGen.initialize(dhSpec);
            KeyPair keypair = keyGen.generateKeyPair();
            System.out.println("KeyPair generated.");
            PrivateKey privateKey = keypair.getPrivate();
            PublicKey publicKey = keypair.getPublic();
            System.out.println(publicKey.getFormat());
            PublicKey rempub = null;
            byte[] ourpublicKeyBytes = publicKey.getEncoded();
            byte[] theirpublicKeyBytes = null;
            System.out.println("Our: " + toHexString(ourpublicKeyBytes));
            oos.writeObject(publicKey);
            Thread.sleep(1000);
            System.out.println("Our public was sent.");
            theirpublicKeyBytes = ((PublicKey) ois.readObject()).getEncoded();
            System.out.println("The: " + toHexString(theirpublicKeyBytes));
            System.out.println("Remote public key is read.");
            X509EncodedKeySpec x509KeySpec = new X509EncodedKeySpec(theirpublicKeyBytes);
            KeyFactory keyFact = KeyFactory.getInstance("DH", "BC");
            rempub = keyFact.generatePublic(x509KeySpec);
            DHParameterSpec paramspec = ((DHPublicKey) rempub).getParams();
            KeyAgreement ka = KeyAgreement.getInstance("DH");
            ka.init(privateKey);
            ka.doPhase(rempub, true);
            String algorithm = "TripleDES";
            SecretKey secretkey = ka.generateSecret(algorithm);
            System.out.println(toHexString(secretkey.getEncoded()));
            SecretKeySpec skeySpec = new SecretKeySpec(secretkey.getEncoded(), algorithm);
            Cipher c = Cipher.getInstance(algorithm);
            c.init(Cipher.ENCRYPT_MODE, skeySpec);
            oos.flush();
            oos.close();
            os.flush();
            os.close();
            os2 = con.openOutputStream();
            oos = new ObjectOutputStream(os2);
            long ttim = System.currentTimeMillis();
            org.jdom.Document doc = new NewXMLtoMolecule(new File("xml/VX.xml")).getDocument();
            SealedObject so = new SealedObject(doc, c);
            oos.writeObject(so);
            oos.flush();
            System.out.println("Time taken:" + (System.currentTimeMillis() - ttim));
            oos.flush();
            oos.close();
            os2.flush();
            os2.close();
            con.close();
        } catch (Exception e2) {
            e2.printStackTrace();
        }
        System.out.println("The image was sent");
    }
