    public static void main(String[] args) {
        System.out.println("Chapter 4: example FoxDogList2");
        System.out.println("-> Creates a PDF file with the text");
        System.out.println("   'Quick brown fox jumps over the lazy dog';");
        System.out.println("   the text is added using List objects.");
        System.out.println("-> jars needed: iText.jar");
        System.out.println("-> resulting PDF: fox_list2.pdf");
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream("results/in_action/chapter04/fox_dog_list2.pdf"));
            document.open();
            Phrase phrase = new Phrase("Quick brown fox jumps over");
            document.add(phrase);
            RomanList romanlist;
            romanlist = new RomanList(20);
            romanlist.setLowercase(true);
            romanlist.add(new ListItem("the lazy dog"));
            romanlist.add(new ListItem("the lazy cat"));
            document.add(romanlist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            romanlist = new RomanList(20);
            romanlist.setLowercase(false);
            romanlist.add(new ListItem("the lazy dog"));
            romanlist.add(new ListItem("the lazy cat"));
            document.add(romanlist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            GreekList greeklist;
            greeklist = new GreekList(20);
            greeklist.setLowercase(true);
            greeklist.add(new ListItem("the lazy dog"));
            greeklist.add(new ListItem("the lazy cat"));
            document.add(greeklist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            greeklist = new GreekList(20);
            greeklist.setLowercase(false);
            greeklist.add(new ListItem("the lazy dog"));
            greeklist.add(new ListItem("the lazy cat"));
            document.add(greeklist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            ZapfDingbatsList zapfdingbatslist;
            zapfdingbatslist = new ZapfDingbatsList(42, 15);
            zapfdingbatslist.add(new ListItem("the lazy dog"));
            zapfdingbatslist.add(new ListItem("the lazy cat"));
            document.add(zapfdingbatslist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            ZapfDingbatsNumberList zapfdingbatsnumberlist;
            zapfdingbatsnumberlist = new ZapfDingbatsNumberList(0, 15);
            zapfdingbatsnumberlist.add(new ListItem("the lazy dog"));
            zapfdingbatsnumberlist.add(new ListItem("the lazy cat"));
            document.add(zapfdingbatsnumberlist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            zapfdingbatsnumberlist = new ZapfDingbatsNumberList(1, 15);
            zapfdingbatsnumberlist.add(new ListItem("the lazy dog"));
            zapfdingbatsnumberlist.add(new ListItem("the lazy cat"));
            document.add(zapfdingbatsnumberlist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            zapfdingbatsnumberlist = new ZapfDingbatsNumberList(2, 15);
            zapfdingbatsnumberlist.add(new ListItem("the lazy dog"));
            zapfdingbatsnumberlist.add(new ListItem("the lazy cat"));
            document.add(zapfdingbatsnumberlist);
            document.add(Chunk.NEWLINE);
            document.add(phrase);
            zapfdingbatsnumberlist = new ZapfDingbatsNumberList(3, 15);
            zapfdingbatsnumberlist.add(new ListItem("the lazy dog"));
            zapfdingbatsnumberlist.add(new ListItem("the lazy cat"));
            document.add(zapfdingbatsnumberlist);
        } catch (DocumentException de) {
            System.err.println(de.getMessage());
        } catch (IOException ioe) {
            System.err.println(ioe.getMessage());
        }
        document.close();
    }
