    public static byte[] createCustomDoc(Prescription rx, double width, double height) throws DocumentException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        int w = (int) width * 72;
        int h = (int) height * 72;
        Rectangle pageSize = new Rectangle(w, h);
        Document document = new Document(pageSize, 10, 10, 10, 10);
        PdfWriter writer = PdfWriter.getInstance(document, baos);
        document.open();
        Paragraph clinic = makeBoldParagraph("CLINIC NAME", 14);
        clinic.setAlignment(Element.ALIGN_CENTER);
        document.add(clinic);
        Paragraph street = makeParagraph("CLINIC ADDRESS", 8);
        street.setAlignment(Element.ALIGN_CENTER);
        document.add(street);
        Paragraph city = makeParagraph("CLINIC STATE/PROVINCE/POSTAL CODE", 8);
        city.setAlignment(Element.ALIGN_CENTER);
        document.add(city);
        Paragraph numbers = makeParagraph("Phone:  PHONE/FAX", 6);
        numbers.setAlignment(Element.ALIGN_CENTER);
        document.add(numbers);
        Paragraph spacer = makeParagraph("\n", 8);
        document.add(spacer);
        Paragraph name = makeBoldParagraph("Name:  " + rx.getLastName() + ", " + rx.getFirstName(), 8);
        Paragraph ssn = makeParagraph("SSN:  " + rx.getSsn(), 8);
        Paragraph phone = makeParagraph("Patient phone:  " + rx.getPhone(), 8);
        String addr = "Address:\n" + rx.getAddress() + "\n" + rx.getCity() + ", " + rx.getState() + "  " + rx.getZip();
        Paragraph ptAddr = makeParagraph(addr, 8);
        Paragraph dateString = makeParagraph("Prescription Date:  " + rx.getDateString(), 8);
        Paragraph doctor = makeBoldParagraph("Physician:  " + rx.getPhysician(), 8);
        Paragraph deanum = makeRedBoldParagraph("DEA Number:  " + rx.getDeaNum(), 8);
        Paragraph serial = makeSerialParagraph("Serial:  " + rx.getKey(), 8);
        Paragraph sigLine = makeBoldParagraph("______________________________________", 8);
        Paragraph diagnosis = makeParagraph("Diagnosis:  " + rx.getDiagnosis(), 8);
        Paragraph stamp = makeBoldParagraph("Valid only with original signature.", 8);
        Table body = new Table(4);
        float[] widths = { 10f, 30f, 50f, 10f };
        body.setWidths(widths);
        body.setWidth(100f);
        body.setAlignment(Element.ALIGN_CENTER);
        body.setBorderWidth(1);
        body.setPadding(1);
        body.addCell(makeBold_Cell("Qty"));
        body.addCell(makeBold_Cell("Medication"));
        body.addCell(makeBold_Cell("Directions"));
        body.addCell(makeBold_Cell("Refills"));
        body.endHeaders();
        body.addCell(makeCenterCell(rx.getQty()));
        body.addCell(makeCenterCell(rx.getMedication()));
        body.addCell(makeCell(rx.getDirections()));
        body.addCell(makeCenterCell(rx.getRefills()));
        document.add(name);
        document.add(ssn);
        document.add(phone);
        document.add(ptAddr);
        document.add(diagnosis);
        document.add(dateString);
        document.add(spacer);
        document.add(body);
        document.add(spacer);
        sigLine.setAlignment(Element.ALIGN_RIGHT);
        serial.setAlignment(Element.ALIGN_RIGHT);
        doctor.setAlignment(Element.ALIGN_RIGHT);
        deanum.setAlignment(Element.ALIGN_RIGHT);
        stamp.setAlignment(Element.ALIGN_CENTER);
        document.add(sigLine);
        document.add(doctor);
        document.add(deanum);
        document.add(serial);
        document.add(stamp);
        document.close();
        return baos.toByteArray();
    }
